### Update Question Subject ids based on unit id ### 
POST http://localhost:5000/api/v1/question-bank/update-subject
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwZDZkNTZkOTk3MjZjM2FjMDFmOGI0OSIsInJvbGUiOjEsImlhdCI6MTYyNTIwNDM3MiwiZXhwIjoxNjI3Nzk2MzcyfQ.tHwcRYllcGWbSS9Zdcg6ajPdkkS05aJ68Ysz-uQGukA

{
      "unit_id": [
            "60cb3da6cc9b7012dcf94abe",
            "60cb3da6cc9b7012dcf94abf",
            "60d1a4a148a5bb000420a518",
            "60d1a4a148a5bb000420a51c",
            "60d1a4a148a5bb000420a51a"
      ],
      "subject_id":"60c85dc6de9a2670e560f1ea"
}


### Update Question Subject ids based on unit id ### 
GET http://localhost:5000/api/v1/question-bank/questions
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwZDZkNTZkOTk3MjZjM2FjMDFmOGI0OSIsInJvbGUiOjEsImlhdCI6MTYyNTIwNDM3MiwiZXhwIjoxNjI3Nzk2MzcyfQ.tHwcRYllcGWbSS9Zdcg6ajPdkkS05aJ68Ysz-uQGukA

{
      "unit_id": [
            "60d1a4a148a5bb000420a519",
            "60d1a4a148a5bb000420a51b",
            "60d1a4a148a5bb000420a518",
            "60d1a4a148a5bb000420a51c",
            "60d1a4a148a5bb000420a51a"
      ]
}

### Update Old Subjects ### 
POST http://localhost:5000/api/v1/question-bank/update-all-subject
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwZDZkNTZkOTk3MjZjM2FjMDFmOGI0OSIsInJvbGUiOjEsImlhdCI6MTYyNTIwNDM3MiwiZXhwIjoxNjI3Nzk2MzcyfQ.tHwcRYllcGWbSS9Zdcg6ajPdkkS05aJ68Ysz-uQGukA

{
      
      "old_subject_id":"60b62b794b44826738114acd",
      "new_subject_id":"60c85dd9de9a2670e560f1eb"
}

### Update Old Subjects ### 
GET http://localhost:5000/api/v1/question-bank/subject-questions/60c85dd9de9a2670e560f1eb
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwZDZkNTZkOTk3MjZjM2FjMDFmOGI0OSIsInJvbGUiOjEsImlhdCI6MTYyNTIwNDM3MiwiZXhwIjoxNjI3Nzk2MzcyfQ.tHwcRYllcGWbSS9Zdcg6ajPdkkS05aJ68Ysz-uQGukA

### All Questions ### 
GET http://localhost:5000/api/v1/question-bank/all-questions/60bf71d1d38e530a98c857fd/60c85dd9de9a2670e560f1eb
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwZDZkNTZkOTk3MjZjM2FjMDFmOGI0OSIsInJvbGUiOjEsImlhdCI6MTYyODU5NDg2NSwiZXhwIjoxNjMxMTg2ODY1fQ.YVwmqo-PvLcGRkp0kxGsmbXfKQVxX9R85-GfwlSDtgA

### All Questions ### 
GET http://localhost:5000/api/v1/question-bank/all-chapter-questions/60d1a2ac48a5bb000420a501
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwZDZkNTZkOTk3MjZjM2FjMDFmOGI0OSIsInJvbGUiOjEsImlhdCI6MTYyODU5NDg2NSwiZXhwIjoxNjMxMTg2ODY1fQ.YVwmqo-PvLcGRkp0kxGsmbXfKQVxX9R85-GfwlSDtgA

### Unit Questions Count ### 
POST http://localhost:3000/api/v1/question-bank/unit-questions
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwZDZkNTZkOTk3MjZjM2FjMDFmOGI0OSIsInJvbGUiOjEsImlhdCI6MTYyOTE3NjYwNiwiZXhwIjoxNjMxNzY4NjA2fQ.cRJ2yaMdV29jqIL1CQGIdaGbsq8v4UuVz7_e3t-xjaw

{
      "class_id":"610a36d1d48cf79f0292f52d",
      "subject_id":"60cc53337fd9443c34e3aa81",
      "unit_id":"6116117e6a9253006c32974d"
}

### Update Questions ChapterID ### 
POST http://localhost:3000/api/v1/question-bank/update-chapter-id
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwZDZkNTZkOTk3MjZjM2FjMDFmOGI0OSIsInJvbGUiOjEsImlhdCI6MTYyODU5NDg2NSwiZXhwIjoxNjMxMTg2ODY1fQ.YVwmqo-PvLcGRkp0kxGsmbXfKQVxX9R85-GfwlSDtgA

{
      "class_id":"610a36d1d48cf79f0292f52d",
      "subject_id":"60cc53337fd9443c34e3aa81",
      "unit_id":"6116117e6a9253006c32974d"
      "chapter_no":"2"
}

